export enum CHAT_MSG_TYPES {
  TEXT = "TEXT",
  ATTACHMENT = "ATTACHMENT",
}

export enum CHAT_MSG_ATTACHMENT_TYPES {
  VIDEO = "VIDEO",
  IMAGE = "IMAGE",
  FILE = "FILE",
  AUDIO = "AUDIO",
}

export enum CHAT_TYPES {
  CONVERSATION = "CONVERSATION",
  GROUP = "GROUP",
  DUMMY = "DUMMY",
}

export enum ATTACHMENT_DISPLAY_STATUS {
  LOADING,
  LOADED,
  FAILED,
}

export enum AUDIO_RECORDING_STATUS {
  NONE,
  PAUSED,
  RECORDING,
  STOPPED,
}
